### ISSUE TITLE
Возможная опечатка

### ISSUE THREAD

**Issue by lunakoly** [Kotlin-Polytech/Algorithms-2019#1]
**Lesson 1** > _sortTimes()_

Нужно отсортировать время в `HH:MM:SS AM/PM`.
В примере в описании правильным ответом считается:
```
12:40:31 AM   <--- это же больше,
07:26:57 AM   <--- чем это
10:00:03 AM
01:15:19 PM
01:15:19 PM
07:56:14 PM
```

**Comment by gagarski** [comment]
12:40 AM - это 00:40 в 24-часовой системе, опечатки нет.

**Comment by lunakoly** [comment]
Оу. Это было неочевидно. Понял, спасибо
